// Generates migrations/seed.sql from the existing front-end data
// (assets/products.js + assets/i18n.js), so the DB starts in sync with the site.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import vm from "node:vm";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

function loadFrontendData() {
  const sandbox = { window: {}, localStorage: { getItem: () => null, setItem: () => {} } };
  vm.createContext(sandbox);
  for (const f of ["assets/i18n.js", "assets/products.js"]) {
    const code = readFileSync(join(root, f), "utf8");
    vm.runInContext(code, sandbox, { filename: f });
  }
  return {
    I18N: sandbox.window.BTT_I18N,
    PRODUCTS: sandbox.window.BTT_PRODUCTS,
    CAT: sandbox.window.BTT_PRODUCT_CAT,
  };
}

const q = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => Number.isFinite(+v) ? String(+v) : "0";

function main() {
  const { I18N, PRODUCTS, CAT } = loadFrontendData();
  const LANGS = ["ru", "uz", "en"];
  const lines = [];
  lines.push("-- AUTOGENERATED by scripts/gen-seed.mjs — do not edit by hand.");
  lines.push("-- Re-run: npm run seed:gen");
  lines.push("");

  const ids = Object.keys(PRODUCTS).sort((a, b) => +a.slice(1) - +b.slice(1));
  ids.forEach((id, i) => {
    const p = PRODUCTS[id];
    const cat = CAT[p.cat] || {};
    lines.push(
      `INSERT OR REPLACE INTO products (id, category, look, price_now, price_old, default_size, active, sort) VALUES ` +
      `(${q(id)}, ${q(p.cat)}, ${q(p.look)}, ${n(p.now)}, ${n(p.old)}, ${n(cat.defSize || 0)}, 1, ${i});`,
    );
    for (const lang of LANGS) {
      const dict = I18N[lang] || {};
      const name = dict[`${id}.name`] || "";
      const catLabel = dict[`${id}.cat`] || "";
      const t = (cat[lang] || cat.ru || {});
      const desc = t.desc || "";
      const sizesObj = cat.sizes;
      const sizes = Array.isArray(sizesObj) ? sizesObj : (sizesObj && (sizesObj[lang] || sizesObj.ru)) || [];
      const specs = { mat: t.mat, dim: t.dim, fin: t.fin, wt: t.wt, seat: t.seat, made: t.made };
      lines.push(
        `INSERT OR REPLACE INTO product_i18n (product_id, lang, name, category_label, description, sizes, specs) VALUES ` +
        `(${q(id)}, ${q(lang)}, ${q(name)}, ${q(catLabel)}, ${q(desc)}, ${q(JSON.stringify(sizes))}, ${q(JSON.stringify(specs))});`,
      );
    }
    lines.push("");
  });

  // A couple of sample articles so the blog + CRM have content to show.
  lines.push(
    `INSERT OR REPLACE INTO articles (id, slug, status, published_at) VALUES ` +
    `(1, 'iskusstvennyy-rotang', 'published', datetime('now'));`,
  );
  const art1 = {
    ru: { title: "Что такое искусственный ротанг", excerpt: "Разбираемся, из чего сделано плетение и почему оно служит годами.", body: "Искусственный ротанг — это прочное волокно, окрашенное в массе. Оно не выгорает на солнце, не боится влаги и мороза и не требует особого ухода." },
    uz: { title: "Sun'iy rotang nima", excerpt: "To'quv nimadan tayyorlangani va nega yillar xizmat qilishini ko'ramiz.", body: "Sun'iy rotang — massasiga bo'yalgan mustahkam tola. Quyoshda rangi o'chmaydi, namlik va sovuqdan qo'rqmaydi va alohida parvarish talab qilmaydi." },
    en: { title: "What is synthetic rattan", excerpt: "A look at what the weave is made of and why it lasts for years.", body: "Synthetic rattan is a durable fibre dyed all the way through. It won't fade in the sun, isn't afraid of moisture or frost and needs no special care." },
  };
  for (const lang of LANGS) {
    const a = art1[lang];
    lines.push(
      `INSERT OR REPLACE INTO article_i18n (article_id, lang, title, excerpt, body) VALUES ` +
      `(1, ${q(lang)}, ${q(a.title)}, ${q(a.excerpt)}, ${q(a.body)});`,
    );
  }
  lines.push("");
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('phone', '+998 71 200 18 46');`);
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('whatsapp', '998712001846');`);
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('telegram', 'bententrade');`);
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('email', 'hello@bententrade.uz');`);
  lines.push("");

  const out = join(root, "migrations", "seed.sql");
  writeFileSync(out, lines.join("\n"), "utf8");
  console.log(`Wrote ${out} (${ids.length} products × ${LANGS.length} langs).`);
}

main();
