// Generates migrations/seed.sql from data/products-master.json + data/articles.json
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const q = (v) => (v == null ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
const n = (v) => (Number.isFinite(+v) ? String(+v) : "0");

function main() {
  const MASTER = JSON.parse(readFileSync(join(root, "data/products-master.json"), "utf8"));
  const LANGS = ["ru", "uz", "en"];
  const lines = [];

  lines.push("-- AUTOGENERATED by scripts/gen-seed.mjs - do not edit by hand.");
  lines.push("-- Re-run: node scripts/gen-seed.mjs");
  lines.push("");
  lines.push("-- Clean old products, i18n, media, aliases");
  lines.push("DELETE FROM product_i18n;");
  lines.push("DELETE FROM media WHERE product_id IS NOT NULL;");
  lines.push("DELETE FROM product_aliases;");
  lines.push("DELETE FROM products;");
  lines.push("");

  // 1. Insert 15 canonical products & aliases
  MASTER.forEach((p, i) => {
    lines.push(
      `INSERT OR REPLACE INTO products (id, category, look, price_now, price_old, default_size, active, sort) VALUES ` +
        `(${q(p.slug)}, ${q(p.category)}, ${q(p.slug)}, ${n(p.price)}, 0, 0, 1, ${i});`,
    );

    if (p.legacyId) {
      lines.push(
        `INSERT OR REPLACE INTO product_aliases (alias, product_id) VALUES (${q(p.legacyId)}, ${q(p.slug)});`,
      );
    }

    for (const lang of LANGS) {
      const i18nObj = (p.i18n && (p.i18n[lang] || p.i18n.ru)) || {};
      const name = i18nObj.name || p.model;
      const catLabel = i18nObj.category_label || p.category;
      const desc = i18nObj.description || "";
      const sizes = [p.dimensions];
      const specs = {
        mat: (p.materials || []).join(", "),
        dim: p.dimensions,
        maxLoad: p.maxLoad || "",
        colors: (p.confirmedColors || []).map((c) => (c.name && (c.name[lang] || c.name.ru)) || c.id).join(", "),
      };

      lines.push(
        `INSERT OR REPLACE INTO product_i18n (product_id, lang, name, category_label, description, sizes, specs) VALUES ` +
          `(${q(p.slug)}, ${q(lang)}, ${q(name)}, ${q(catLabel)}, ${q(desc)}, ${q(JSON.stringify(sizes))}, ${q(JSON.stringify(specs))});`,
      );
    }

    // Media entries
    if (Array.isArray(p.images)) {
      p.images.forEach((imgKey, imgIdx) => {
        lines.push(
          `INSERT INTO media (key, product_id, alt, sort) VALUES (${q(imgKey)}, ${q(p.slug)}, ${q(p.model)}, ${imgIdx});`,
        );
      });
    }
    lines.push("");
  });

  // Seed all blog & SEO articles into the database so the blog + CRM are rich and populated.
  const a1Raw = JSON.parse(readFileSync(join(root, "data/articles.json"), "utf8"));
  const a2Raw = JSON.parse(readFileSync(join(root, "data/articles-seo.json"), "utf8"));
  const allArticles = [
    ...(Array.isArray(a1Raw) ? a1Raw : a1Raw.articles || []),
    ...(Array.isArray(a2Raw) ? a2Raw : a2Raw.articles || []),
  ];

  let artId = 1;
  const seenSlugs = new Set();
  for (const art of allArticles) {
    if (!art.slug || seenSlugs.has(art.slug)) continue;
    seenSlugs.add(art.slug);
    const pub = art.published_at || "2026-03-01";
    const cover = art.cover_media || "assets/hero-garden-furniture.png";
    lines.push(
      `INSERT OR REPLACE INTO articles (id, slug, cover_media, status, published_at) VALUES ` +
        `(${artId}, ${q(art.slug)}, ${q(cover)}, 'published', ${q(pub)});`,
    );
    for (const lang of LANGS) {
      const a = (art.i18n && (art.i18n[lang] || art.i18n.ru)) || {};
      lines.push(
        `INSERT OR REPLACE INTO article_i18n (article_id, lang, title, excerpt, body) VALUES ` +
          `(${artId}, ${q(lang)}, ${q(a.title || "")}, ${q(a.excerpt || "")}, ${q(a.body || "")});`,
      );
    }
    artId++;
  }
  lines.push("");
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('brand', 'BTT - мебель для дома и сада');`);
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('phone', '+998 77 104 44 22');`);
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('whatsapp', '998771044422');`);
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('telegram', 'bententradeuz');`);
  lines.push(`INSERT OR REPLACE INTO settings (key, value) VALUES ('email', 'hello@bententrade.uz');`);
  lines.push("");

  const out = join(root, "migrations", "seed.sql");
  writeFileSync(out, lines.join("\n"), "utf8");
  console.log(`Wrote ${out} (${MASTER.length} canonical SKUs + ${MASTER.length} aliases × ${LANGS.length} langs).`);
}

main();
