-- SAFE PRODUCTION SYNC SCRIPT (Zero Data Loss, Targeted Updates Only)

UPDATE products SET price_now = 188000 WHERE id = 'stul-roero';
UPDATE products SET price_now = 212000 WHERE id = 'stul-noero';
UPDATE products SET price_now = 236000 WHERE id = 'stul-todo';
UPDATE products SET price_now = 344000 WHERE id = 'stul-jardin';

DELETE FROM media WHERE product_id = 'stol-vertex-80';
INSERT INTO media (key, product_id, alt, sort) VALUES ('assets/placeholder.svg', 'stol-vertex-80', 'Vertex 80', 0);
DELETE FROM media WHERE product_id = 'stol-corda-135' AND key = 'assets/prod-table-taper-135-white-scene.jpg';

UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-vertex' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-vertex' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-vertex' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-corda' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-corda' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-corda' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-roero' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-roero' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-roero' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-noero' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-noero' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-noero' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-todo' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-todo' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-todo' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-todo-soft' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-todo-soft' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-todo-soft' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-jardin' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-jardin' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-jardin' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-lira' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-lira' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stul-lira' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'kreslo-como' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'kreslo-como' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'kreslo-como' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-rotang-80' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-rotang-80' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-rotang-80' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-vertex-d90' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-vertex-d90' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-vertex-d90' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-rotang-135' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-rotang-135' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-rotang-135' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-80' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-80' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-80' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-vertex-80' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-vertex-80' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-vertex-80' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-135' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-135' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-taper-135' AND lang = 'en';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-corda-135' AND lang = 'ru';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-corda-135' AND lang = 'uz';
UPDATE product_i18n SET description = '', seo_title = '', seo_description = '' WHERE product_id = 'stol-corda-135' AND lang = 'en';
